{
 "title": "Nop Commerce",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Approved Payments",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "checkout_payments_approved_total{payment_method=\"Payments.Manual\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rejected Payments",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "checkout_payments_rejected_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(max_over_time(checkout_payments_rejected_total[1h])) / (sum(max_over_time(checkout_payments_rejected_total[1h])) + sum(max_over_time(checkout_payments_approved_total[1h])))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Payment Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 9 },
   "targets": [
    { "operation": "PlaceOrder", "service": "NopCommerce-Loja" }
   ]
  },
  {
   "title": "All Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 9 },
   "targets": [
    { "service": "NopCommerce-Loja" }
   ]
  }
 ]
}